# Generated by Django 5.2.9 on 2025-12-30 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_profile_cv_alter_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cv',
        ),
    ]
