# Generated by Django 5.2.9 on 2025-12-30 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_user_bio_remove_user_cv'),
        ('dashboard', '0005_alter_lesson_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lessons',
            field=models.ManyToManyField(blank=True, related_name='users', to='dashboard.lesson'),
        ),
    ]
