# Generated by Django 5.2.9 on 2025-12-30 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_user_lessons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='lessons',
        ),
    ]
