# Generated by Django 5.2.9 on 2026-01-05 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_course_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='profile',
        ),
    ]
