# Generated by Django 5.2.9 on 2026-01-04 20:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New Lesson', max_length=150)),
                ('slug', models.CharField(default='', max_length=150)),
                ('content', models.TextField(blank=True, max_length=2000)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='lesson_thumbnails/%y/%m/%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png'])])),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
            options={
                'verbose_name': 'Lesson',
                'ordering': ['-created_at'],
            },
        ),
    ]
